<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class UsuariosSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('users')->insert([
            [
                'DNI' => '45678901D',
                'name' => 'Ana',
                'apellido_uno' => 'Rodríguez',
                'apellido_dos' => 'Gutiérrez',
                'fecha_nac' => '1980-03-12',
                'telefono' => 633218765,
                'direccion' => 'Calle Flores, 87',
                'cp' => 29004,
                'poblacion' => 'Málaga',
                'email' => 'ana@gmail.com',
                'password' => bcrypt('contrasenia1234'),
                'perfil_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'DNI' => '56789012E',
                'name' => 'Carlos',
                'apellido_uno' => 'Jiménez',
                'apellido_dos' => 'Vega',
                'fecha_nac' => '1987-08-28',
                'telefono' => 611234567,
                'direccion' => 'Avenida Costa, 34',
                'cp' => 29005,
                'poblacion' => 'Málaga',
                'email' => 'carlos@yahoo.com',
                'password' => bcrypt('contrasenia1234'),
                'perfil_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'DNI' => '62348901L',
                'name' => 'Claudia',
                'apellido_uno' => 'García',
                'apellido_dos' => 'López',
                'fecha_nac' => '1982-05-07',
                'telefono' => 995408765,
                'direccion' => 'Calle Barca, 12',
                'cp' => 29010,
                'poblacion' => 'Málaga',
                'email' => 'claudia@gmail.com',
                'password' => bcrypt('contrasenia1234'),
                'perfil_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'DNI' => '33518901D',
                'name' => 'Javier',
                'apellido_uno' => 'Martinez',
                'apellido_dos' => 'Bellido',
                'fecha_nac' => '1999-10-06',
                'telefono' => 432118005,
                'direccion' => 'Calle Trinidad, 27',
                'cp' => 29013,
                'poblacion' => 'Málaga',
                'email' => 'javier@gmail.com',
                'password' => bcrypt('contrasenia1234'),
                'perfil_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'DNI' => '98548901X',
                'name' => 'Paloma',
                'apellido_uno' => 'Navarro',
                'apellido_dos' => 'Aguilar',
                'fecha_nac' => '1999-10-08',
                'telefono' => 612018765,
                'direccion' => 'Avenida Rey, 9',
                'cp' => 29011,
                'poblacion' => 'Málaga',
                'email' => 'paloma@gmail.com',
                'password' => bcrypt('contrasenia1234'),
                'perfil_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'DNI' => '54903701X',
                'name' => 'Isabel',
                'apellido_uno' => 'Montero',
                'apellido_dos' => 'Aguilar',
                'fecha_nac' => '1994-03-02',
                'telefono' => 334018765,
                'direccion' => 'Avenida Aguadulce, 5',
                'cp' => 29012,
                'poblacion' => 'Málaga',
                'email' => 'isabel@gmail.com',
                'password' => bcrypt('contrasenia1234'),
                'perfil_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'DNI' => '12345678A',
                'name' => 'María',
                'apellido_uno' => 'García',
                'apellido_dos' => 'López',
                'fecha_nac' => '1990-05-15',
                'telefono' => 612345678,
                'direccion' => 'Calle Sol, 123',
                'cp' => 29001,
                'poblacion' => 'Málaga',
                'email' => 'maria@gmail.com',
                'password' => bcrypt('contrasenia1234'),
                'perfil_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'DNI' => '23456789B',
                'name' => 'David',
                'apellido_uno' => 'Martínez',
                'apellido_dos' => 'Ramírez',
                'fecha_nac' => '1985-09-22',
                'telefono' => 655432189,
                'direccion' => 'Avenida Principal, 45',
                'cp' => 29002,
                'poblacion' => 'Málaga',
                'email' => 'david@yahoo.com',
                'password' => bcrypt('contrasenia1234'),
                'perfil_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'DNI' => '34567890C',
                'name' => 'Nuria',
                'apellido_uno' => 'Fernández',
                'apellido_dos' => 'Gómez',
                'fecha_nac' => '1988-11-30',
                'telefono' => 622345678,
                'direccion' => 'Plaza Central, 7',
                'cp' => 29003,
                'poblacion' => 'Málaga',
                'email' => 'nuria@hotmail.com',
                'password' => bcrypt('contrasenia1234'),
                'perfil_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'DNI' => '65002884D',
                'name' => 'Susana',
                'apellido_uno' => 'Cabello',
                'apellido_dos' => 'Gómez',
                'fecha_nac' => '1998-11-30',
                'telefono' => 622345678,
                'direccion' => 'Plaza Central, 7',
                'cp' => 29003,
                'poblacion' => 'Málaga',
                'email' => 'susana@gmail.com',
                'password' => bcrypt('contrasenia1234'),
                'perfil_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
